Feature/sonar sensor
ThundeRatz/gazebo_modelo_carrinho pull request #3
Opened 2021-03-16 18:26 UTC by mariarezende07

Adicionamos o sensor ultrassonico ao modelo e arrumamos o spawn para que o carrinho esteja dentro da pista.

2021-03-16 18:49 UTC, FelipeGdM requested changes
As mudanças estão show de bola, só ficou faltando a possibilidade de habilitar o cone de detecção do sensor

2021-03-16 18:49 UTC, FelipeGdM commented on urdf/modelo_carrinho.gazebo
> +  <xacro:ultrasonic_sensor link_reference="sonar_link" topic_name="ultrasonic/reading"/>
Acho que seria interessante deixar a opção de habilitar a visualização do campo de visão do sensor. Eu achei particularmente divertido ver o cone de detecção do sensor, acho que pode cumprir uma função didática para os alunos

No simulador do VSS nós fazemos uma "construção condicional" dos robôs, afinal cada robô tem um conjunto de cores distinto. O modo de se fazer isso está exemplificado [nesse arquivo xacro](https://github.com/ThundeRatz/vss_simulation/blob/242227a86614d06a5e488483c38abb28a8a805c9/urdf/generic_vss_team.gazebo) e nessa [linha do launchfile](https://github.com/ThundeRatz/vss_simulation/blob/242227a86614d06a5e488483c38abb28a8a805c9/launch/spawn_robot.launch#L18)

2021-03-16 19:12 UTC, LucasHaug requested changes
Não sei se vocês já viram isso, mas com a angulação do sensor ele tá sempre vendo o chão muito perto, aí o maior valor que ele consegue ler aqui é de uns 7~8 cm, então a gente só conseguiria ver a parede quando tivesse mais perto que isso aí. Não é um problema do plugin em si, assim dá pra mudar o range vertical né, mas acho que faz mais sentido mudar a posição do sensor, é algo que seria bom arrumar acho pro modelo que a gente vai passar.

![image](https://user-images.githubusercontent.com/39196309/111366050-ccc7ba80-8671-11eb-96c6-9bd762f07978.png)

2021-03-16 19:37 UTC, lucastrschneider commented
> Não sei se vocês já viram isso, mas com a angulação do sensor ele tá sempre vendo o chão muito perto, aí o maior valor que ele consegue ler aqui é de uns 7~8 cm, então a gente só conseguiria ver a parede quando tivesse mais perto que isso aí. Não é um problema do plugin em si, assim dá pra mudar o range vertical né, mas acho que faz mais sentido mudar a posição do sensor, é algo que seria bom arrumar acho pro modelo que a gente vai passar.
> 
> ![image](https://user-images.githubusercontent.com/39196309/111366050-ccc7ba80-8671-11eb-96c6-9bd762f07978.png)

É, a gente tava mudando a inclinação do link do sensor aqui na mão para poder testar auhsuuashuhu

Mas tipo, tem uma correção para fazer ai também, pq o cone tá um pouco maior do que deveria pelo datasheet do sensor, então ja ajudaria um pouco, mas mesmo assim, seria melhor deixar ele apontando para frente.

2021-03-16 20:47 UTC, lucastrschneider commented on urdf/modelo_carrinho.gazebo
> +  <xacro:ultrasonic_sensor link_reference="sonar_link" topic_name="ultrasonic/reading"/>
Boa! Colocamos a possibilidade nos launch files e nos xacros agora também

2021-03-16 21:30 UTC, LucasHaug approved these changes

2021-03-16 21:45 UTC, lucastrschneider commented
Só para deixar registrado, nós nos baseamos no [datasheet](https://www.electroschematics.com/wp-content/uploads/2013/07/HCSR04-datasheet-version-1.pdf) do sensor HC - SR04 para configurar os parâmetros do plugin.

Uma coisa que não ficou muito clara foi dentro da tag <scan>, onde temos configurações para os raios horizontais e verticais. Além do número de samples e dos angulos máximos e mínimos que os raios teriam, temos também um parâmetro <resolution>, Em vários lugares que olhamos, esse parâmtro estava setado como 1. Não conseguimos achar um tutorial com o Gazebo usando ROS 1, mas tem o [tutorial do ignition](https://ignitionrobotics.org/docs/citadel/sensors) sobre sensores que explica mais ou menos para que ele serve:

> resolution: this number is multiplied by samples to determine the number range data points.

Mas mesmo com essa definição, não entendemos muito bem para que servia, então deixamos em 1 mesmo, igual estava no exemplo do tutorial.

Parece estar funcionando certinho, mas se alguém souber o que ele é e para que ele serve, manda ai dps kkkkkk

2021-03-16 21:53 UTC, lucastrschneider commented
Voltando agora sobre a questão do sensor apontando para baixo e muito perto do chão, nós percebemos também que ele estava lendo um pouco a borda da pista. Dessa forma, a distancia máxima que ele enxergava era de 10 cm, equando chegava perto das extremidades da pista, ele ainda ficava confuso ao ler as bordas.

Para corrigir isso, inclinamos o link do sonar um poco para tras e elevamos em 2 cm em relação a base, só para ver como a leitura ficava, como pode ser visto nas figuras abaixo.

![image](https://user-images.githubusercontent.com/50970346/111384463-4bc7ed80-8688-11eb-8bb5-d06a6d49608f.png)

![image](https://user-images.githubusercontent.com/50970346/111384482-52566500-8688-11eb-8a38-65dc77da9036.png)

Dessa forma, a distância máxima chegou a 60 cm mais ou menos, e ele não pegava mais as bordas da pista quando chegava perto. Por isso, acho válido talvez fazer umas pequenas mudanças no CAD do modelo, principalmente em relação à inclinação, mas também manter isso em mente para não deixar acontecer nos projetos dos bixos, se não eles provavelmente vão ter problema dps.

2021-03-16 22:45 UTC, FelipeGdM approved these changes

2021-03-16 23:10 UTC, LucasHaug commented
> Só para deixar registrado, nós nos baseamos no [datasheet](https://www.electroschematics.com/wp-content/uploads/2013/07/HCSR04-datasheet-version-1.pdf) do sensor HC - SR04 para configurar os parâmetros do plugin.
> 
> Uma coisa que não ficou muito clara foi dentro da tag , onde temos configurações para os raios horizontais e verticais. Além do número de samples e dos angulos máximos e mínimos que os raios teriam, temos também um parâmetro , Em vários lugares que olhamos, esse parâmtro estava setado como 1. Não conseguimos achar um tutorial com o Gazebo usando ROS 1, mas tem o [tutorial do ignition](https://ignitionrobotics.org/docs/citadel/sensors) sobre sensores que explica mais ou menos para que ele serve:
> 
> > resolution: this number is multiplied by samples to determine the number range data points.
> 
> Mas mesmo com essa definição, não entendemos muito bem para que servia, então deixamos em 1 mesmo, igual estava no exemplo do tutorial.
> 
> Parece estar funcionando certinho, mas se alguém souber o que ele é e para que ele serve, manda ai dps kkkkkk

Então, registrando aqui, pelo o que eu vi o que acontece é o `samples` é o número de fato de amostras do simulador que você vai pegar, se a sua resolução for 1, coxa cada amostra vai ser um raio simulado, senão vão ser feitas interpolações entre as amostras pra determinar os raios. O passo angular entre cada raio é `(max_range - min_range) / (samples * resolution)`, de acordo com esse passo angular, ele vai ver o ponto que você quer e fazer uma interpolação com os dados amostrados pra determinar o raio. Se quiserem ver as contas dá pra ver o código [aqui](https://github.com/osrf/gazebo/blob/gazebo11/gazebo/sensors/RaySensor.cc) e também tem essa documentaçãozinha do GpuRay pra complementar:

https://github.com/osrf/gazebo/blob/2df3bfb039c1f5616122a0452ece99a8f3395e17/gazebo/sensors/GpuRaySensor.hh#L131-L136

2021-03-18 15:25 UTC, lucastrschneider approved these changes

2021-03-18 15:35 UTC, LucasHaug approved these changes

2021-03-19 16:54 UTC, merged